version: "3.9"
services:
  dog-backend:
    build: .
    container_name: dog-backend
    ports:
      - "8000:8000"
    env_file:
      - .env_example
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: database
    env_file:
      - .env_example
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: